export type Cut = {
  id: string;
  title: string;
  en: string;
  duration: number;
  src: string;
  poster: string;
  audio: string;
  note: string;
  fileName: string;
  series: "crystal" | "glass";
};

export type Still = {
  id: string;
  title: string;
  en: string;
  src: string;
  fileName: string;
};

export type AtelierModule = {
  id: string;
  title: string;
  en: string;
  blurb: string;
  cover: string;
  cuts: Cut[];
  stills: Still[];
};

const STEAK_CUTS: Cut[] = [
  {
    id: "crystal-overhead",
    title: "四片",
    en: "Four",
    duration: 15,
    src: "/media/crystal-overhead.mp4",
    poster: "/media/poster-crystal-overhead.jpg",
    audio: "/media/crystal-overhead.m4a",
    note: "俯拍连切四刀，晶片依次倒下，石面清脆作响。",
    fileName: "crystal-steak-four-overhead.mp4",
    series: "crystal",
  },
  {
    id: "crystal-succession",
    title: "连切",
    en: "Cuts",
    duration: 15,
    src: "/media/crystal-succession.mp4",
    poster: "/media/poster-crystal-succession.jpg",
    audio: "/media/crystal-succession.m4a",
    note: "从整块水晶肋眼连切四刀，刀起片落。",
    fileName: "crystal-steak-succession.mp4",
    series: "crystal",
  },
  {
    id: "crystal-four",
    title: "立片",
    en: "Slabs",
    duration: 15,
    src: "/media/crystal-four.mp4",
    poster: "/media/poster-crystal-four.jpg",
    audio: "/media/crystal-four.m4a",
    note: "侧刀连切，三到四片水晶立在案上。",
    fileName: "crystal-steak-slabs.mp4",
    series: "crystal",
  },
  {
    id: "crystal-fall",
    title: "倾倒",
    en: "Fall",
    duration: 10,
    src: "/media/crystal-fall.mp4",
    poster: "/media/poster-crystal-fall.jpg",
    audio: "/media/crystal-fall.m4a",
    note: "四片晶面依次倾倒，碰撞出清脆铃声。",
    fileName: "crystal-steak-fall.mp4",
    series: "crystal",
  },
  {
    id: "crystal-topple",
    title: "倒下",
    en: "Topple",
    duration: 15,
    src: "/media/crystal-topple.mp4",
    poster: "/media/poster-crystal-topple.jpg",
    audio: "/media/crystal-topple.m4a",
    note: "切片被刀锋推倒，晶片落在花岗岩上。",
    fileName: "crystal-steak-topple.mp4",
    series: "crystal",
  },
  {
    id: "side",
    title: "侧切",
    en: "Side",
    duration: 15,
    src: "/media/side.mp4",
    poster: "/media/poster-side.jpg",
    audio: "/media/side.m4a",
    note: "刀锋从侧面缓缓剖开琥珀玻璃肋眼。",
    fileName: "glass-steak-side.mp4",
    series: "glass",
  },
  {
    id: "press",
    title: "下压",
    en: "Press",
    duration: 15,
    src: "/media/press.mp4",
    poster: "/media/poster-press.jpg",
    audio: "/media/press.m4a",
    note: "整刀下压，晶面碎裂后层层分离。",
    fileName: "glass-steak-press.mp4",
    series: "glass",
  },
  {
    id: "split",
    title: "对开",
    en: "Split",
    duration: 10,
    src: "/media/split.mp4",
    poster: "/media/poster-split.jpg",
    audio: "/media/split.m4a",
    note: "从右侧切入，牛排对半打开。",
    fileName: "glass-steak-split.mp4",
    series: "glass",
  },
  {
    id: "hand",
    title: "俯切",
    en: "Overhead",
    duration: 10,
    src: "/media/hand.mp4",
    poster: "/media/poster-hand.jpg",
    audio: "/media/hand.m4a",
    note: "俯拍持刀，完整切开这块玻璃肋眼。",
    fileName: "glass-steak-overhead.mp4",
    series: "glass",
  },
  {
    id: "egg",
    title: "荷包蛋",
    en: "Egg",
    duration: 15,
    src: "/media/steak-egg.mp4",
    poster: "/media/poster-steak-egg.jpg",
    audio: "/media/steak-egg.m4a",
    note: "大理石板上煎一枚玻璃荷包蛋，无火，油边翻滚，玻璃刀对切开黄。",
    fileName: "glass-egg.mp4",
    series: "glass",
  },
  {
    id: "egg-sizzle",
    title: "煎边",
    en: "Sizzle",
    duration: 15,
    src: "/media/steak-egg-sizzle.mp4",
    poster: "/media/poster-steak-egg-sizzle.jpg",
    audio: "/media/steak-egg-sizzle.m4a",
    note: "热气与油花，玻璃刀切中，刀碰大理石清脆作响。",
    fileName: "glass-egg-sizzle.mp4",
    series: "glass",
  },
  {
    id: "egg-yolk",
    title: "蛋黄",
    en: "Yolk",
    duration: 15,
    src: "/media/steak-egg-yolk.mp4",
    poster: "/media/poster-steak-egg-yolk.jpg",
    audio: "/media/steak-egg-yolk.m4a",
    note: "切开后粘稠蛋黄流出，带着液体声。",
    fileName: "glass-egg-yolk.mp4",
    series: "glass",
  },
];

const STEAK_STILLS: Still[] = [
  {
    id: "crystal-hero",
    title: "水晶整块",
    en: "Crystal",
    src: "/media/crystal-hero.jpg",
    fileName: "crystal-steak-hero.jpg",
  },
  {
    id: "crystal-slices",
    title: "四片晶面",
    en: "Slices",
    src: "/media/crystal-slices.jpg",
    fileName: "crystal-steak-slices.jpg",
  },
  {
    id: "hero",
    title: "琥珀整块",
    en: "Whole",
    src: "/media/steak-hero.jpg",
    fileName: "glass-steak-hero.jpg",
  },
  {
    id: "knife",
    title: "落刀",
    en: "Contact",
    src: "/media/steak-knife.jpg",
    fileName: "glass-steak-knife.jpg",
  },
  {
    id: "sliced",
    title: "切开",
    en: "Opened",
    src: "/media/steak-sliced.jpg",
    fileName: "glass-steak-sliced.jpg",
  },
  {
    id: "egg-still",
    title: "荷包蛋",
    en: "Egg",
    src: "/media/steak-egg.jpg",
    fileName: "glass-egg.jpg",
  },
];

const VEG_CUTS: Cut[] = [
  {
    id: "carrot",
    title: "胡萝卜",
    en: "Carrot",
    duration: 15,
    src: "/media/veg-carrot.mp4",
    poster: "/media/poster-veg-carrot.jpg",
    audio: "/media/veg-carrot.m4a",
    note: "橙晶胡萝卜连切三刀，圆片倾倒，石面清脆作响。",
    fileName: "glass-carrot.mp4",
    series: "glass",
  },
  {
    id: "tomato",
    title: "番茄",
    en: "Tomato",
    duration: 15,
    src: "/media/veg-tomato.mp4",
    poster: "/media/poster-veg-tomato.jpg",
    audio: "/media/veg-tomato.m4a",
    note: "红晶番茄连切三刀，切片倒下发出玻璃清响。",
    fileName: "glass-tomato.mp4",
    series: "glass",
  },
  {
    id: "broccoli",
    title: "西蓝花",
    en: "Broccoli",
    duration: 15,
    src: "/media/veg-broccoli.mp4",
    poster: "/media/poster-veg-broccoli.jpg",
    audio: "/media/veg-broccoli.m4a",
    note: "翠绿水晶西蓝花连切两三刀，花蕾晶片落地。",
    fileName: "glass-broccoli.mp4",
    series: "glass",
  },
  {
    id: "cucumber",
    title: "黄瓜",
    en: "Cucumber",
    duration: 15,
    src: "/media/veg-cucumber.mp4",
    poster: "/media/poster-veg-cucumber.jpg",
    audio: "/media/veg-cucumber.m4a",
    note: "翠晶黄瓜连切四刀，圆片倾倒，石面清脆作响。",
    fileName: "glass-cucumber.mp4",
    series: "glass",
  },
  {
    id: "eggplant",
    title: "茄子",
    en: "Eggplant",
    duration: 15,
    src: "/media/veg-eggplant.mp4",
    poster: "/media/poster-veg-eggplant.jpg",
    audio: "/media/veg-eggplant.m4a",
    note: "紫晶茄子连切四刀，切片倒下发出玻璃清响。",
    fileName: "glass-eggplant.mp4",
    series: "glass",
  },
  {
    id: "onion",
    title: "洋葱",
    en: "Onion",
    duration: 15,
    src: "/media/veg-onion.mp4",
    poster: "/media/poster-veg-onion.jpg",
    audio: "/media/veg-onion.m4a",
    note: "金晶洋葱连切四刀，晶片层层倒下。",
    fileName: "glass-onion.mp4",
    series: "glass",
  },
  {
    id: "potato",
    title: "土豆",
    en: "Potato",
    duration: 15,
    src: "/media/veg-potato.mp4",
    poster: "/media/poster-veg-potato.jpg",
    audio: "/media/veg-potato.m4a",
    note: "餐刀先敲两下玻璃土豆，再切两刀，晶片侧倒清脆作响。",
    fileName: "glass-potato.mp4",
    series: "glass",
  },
  {
    id: "potato-tap",
    title: "敲击",
    en: "Tap",
    duration: 15,
    src: "/media/veg-potato-tap.mp4",
    poster: "/media/poster-veg-potato-tap.jpg",
    audio: "/media/veg-potato-tap.m4a",
    note: "刀背轻叩两下，连切两片，切片倒下发出玻璃清响。",
    fileName: "glass-potato-tap.mp4",
    series: "glass",
  },
];

const VEG_STILLS: Still[] = [
  {
    id: "veg-carrot",
    title: "胡萝卜",
    en: "Carrot",
    src: "/media/veg-carrot.jpg",
    fileName: "glass-carrot.jpg",
  },
  {
    id: "veg-tomato",
    title: "番茄",
    en: "Tomato",
    src: "/media/veg-tomato.jpg",
    fileName: "glass-tomato.jpg",
  },
  {
    id: "veg-broccoli",
    title: "西蓝花",
    en: "Broccoli",
    src: "/media/veg-broccoli.jpg",
    fileName: "glass-broccoli.jpg",
  },
  {
    id: "veg-cucumber",
    title: "黄瓜",
    en: "Cucumber",
    src: "/media/veg-cucumber.jpg",
    fileName: "glass-cucumber.jpg",
  },
  {
    id: "veg-eggplant",
    title: "茄子",
    en: "Eggplant",
    src: "/media/veg-eggplant.jpg",
    fileName: "glass-eggplant.jpg",
  },
  {
    id: "veg-onion",
    title: "洋葱",
    en: "Onion",
    src: "/media/veg-onion.jpg",
    fileName: "glass-onion.jpg",
  },
  {
    id: "veg-potato",
    title: "土豆",
    en: "Potato",
    src: "/media/veg-potato.jpg",
    fileName: "glass-potato.jpg",
  },
];

const COSMOS_CUTS: Cut[] = [
  {
    id: "saturn",
    title: "土星",
    en: "Saturn",
    duration: 15,
    src: "/media/cosmos-saturn.mp4",
    poster: "/media/poster-cosmos-saturn.jpg",
    audio: "/media/cosmos-saturn.m4a",
    note: "玻璃土星连切三刀，蜂蜜涌出，晶环碎落。",
    fileName: "glass-saturn.mp4",
    series: "glass",
  },
  {
    id: "saturn-cuts",
    title: "星环",
    en: "Rings",
    duration: 15,
    src: "/media/cosmos-saturn-cuts.mp4",
    poster: "/media/poster-cosmos-saturn-cuts.jpg",
    audio: "/media/cosmos-saturn-cuts.m4a",
    note: "刀锋连切三片，星环掉落，晶片倾倒清脆作响。",
    fileName: "glass-saturn-three.mp4",
    series: "glass",
  },
  {
    id: "saturn-honey",
    title: "蜜核",
    en: "Amber",
    duration: 15,
    src: "/media/cosmos-saturn-honey.mp4",
    poster: "/media/poster-cosmos-saturn-honey.jpg",
    audio: "/media/cosmos-saturn-honey.m4a",
    note: "切口涌出粘稠蜂蜜岩浆，三片立在案上。",
    fileName: "glass-saturn-honey.mp4",
    series: "glass",
  },
  {
    id: "typhoon",
    title: "台风",
    en: "Typhoon",
    duration: 15,
    src: "/media/cosmos-typhoon.mp4",
    poster: "/media/poster-cosmos-typhoon.jpg",
    audio: "/media/cosmos-typhoon.m4a",
    note: "玻璃台风旋转电闪，连切三刀，流水清脆，切块消散。无风声雷声。",
    fileName: "glass-typhoon.mp4",
    series: "glass",
  },
  {
    id: "earth",
    title: "地球",
    en: "Earth",
    duration: 15,
    src: "/media/cosmos-earth.mp4",
    poster: "/media/poster-cosmos-earth.jpg",
    audio: "/media/cosmos-earth.m4a",
    note: "玻璃地球连切三刀，粘稠岩浆顺切口流下，晶片侧倒。",
    fileName: "glass-earth.mp4",
    series: "glass",
  },
  {
    id: "earth-lava",
    title: "岩浆",
    en: "Magma",
    duration: 15,
    src: "/media/cosmos-earth-lava.mp4",
    poster: "/media/poster-cosmos-earth-lava.jpg",
    audio: "/media/cosmos-earth-lava.m4a",
    note: "三片立起，岩浆冷却结壳又被新岩浆覆过。",
    fileName: "glass-earth-lava.mp4",
    series: "glass",
  },
  {
    id: "earth-fall",
    title: "侧倒",
    en: "Tilt",
    duration: 15,
    src: "/media/cosmos-earth-fall.mp4",
    poster: "/media/poster-cosmos-earth-fall.jpg",
    audio: "/media/cosmos-earth-fall.m4a",
    note: "切片侧倒碰撞，岩浆粘稠涌出，清脆作响。",
    fileName: "glass-earth-fall.mp4",
    series: "glass",
  },
  {
    id: "sun",
    title: "太阳",
    en: "Sun",
    duration: 15,
    src: "/media/cosmos-sun-sphere.mp4",
    poster: "/media/poster-cosmos-sun-sphere.jpg",
    audio: "/media/cosmos-sun-sphere.m4a",
    note: "餐刀一剖发光玻璃太阳，两瓣倒下，岩浆抹上玻璃吐司。",
    fileName: "glass-sun.mp4",
    series: "glass",
  },
  {
    id: "blackhole",
    title: "黑洞",
    en: "Hole",
    duration: 15,
    src: "/media/cosmos-blackhole.mp4",
    poster: "/media/poster-cosmos-blackhole.jpg",
    audio: "/media/cosmos-blackhole.m4a",
    note: "玻璃黑洞连切三片，星核发光，切片侧倒，刀子被吸入剩余核。",
    fileName: "glass-blackhole.mp4",
    series: "glass",
  },
  {
    id: "blackhole-pull",
    title: "吸入",
    en: "Pull",
    duration: 15,
    src: "/media/cosmos-blackhole-pull.mp4",
    poster: "/media/poster-cosmos-blackhole-pull.jpg",
    audio: "/media/cosmos-blackhole-pull.m4a",
    note: "三片卸开后，剩余黑洞把餐刀吸进去。",
    fileName: "glass-blackhole-pull.mp4",
    series: "glass",
  },
];

const COSMOS_STILLS: Still[] = [
  {
    id: "saturn-whole",
    title: "整颗",
    en: "Whole",
    src: "/media/cover-saturn.jpg",
    fileName: "glass-saturn.jpg",
  },
  {
    id: "saturn-sliced",
    title: "切开",
    en: "Opened",
    src: "/media/cosmos-saturn-sliced.jpg",
    fileName: "glass-saturn-sliced.jpg",
  },
  {
    id: "typhoon-still",
    title: "台风",
    en: "Typhoon",
    src: "/media/cosmos-typhoon.jpg",
    fileName: "glass-typhoon.jpg",
  },
  {
    id: "earth-still",
    title: "地球",
    en: "Earth",
    src: "/media/cosmos-earth.jpg",
    fileName: "glass-earth.jpg",
  },
  {
    id: "sun-still",
    title: "太阳",
    en: "Sun",
    src: "/media/cosmos-sun-sphere.jpg",
    fileName: "glass-sun.jpg",
  },
  {
    id: "blackhole-still",
    title: "黑洞",
    en: "Hole",
    src: "/media/cosmos-blackhole.jpg",
    fileName: "glass-blackhole.jpg",
  },
];

export const MODULES: AtelierModule[] = [
  {
    id: "steak",
    title: "牛排",
    en: "Steak",
    blurb: "水晶石英、琥珀玻璃肋眼，与煎玻璃荷包蛋。",
    cover: "/media/crystal-hero.jpg",
    cuts: STEAK_CUTS,
    stills: STEAK_STILLS,
  },
  {
    id: "veg",
    title: "蔬菜",
    en: "Vegetables",
    blurb: "玻璃胡萝卜、番茄、西蓝花、黄瓜、茄子、洋葱与土豆。",
    cover: "/media/veg-tomato.jpg",
    cuts: VEG_CUTS,
    stills: VEG_STILLS,
  },
  {
    id: "cosmos",
    title: "宇宙",
    en: "Cosmos",
    blurb: "玻璃土星、台风、地球、太阳与黑洞。",
    cover: "/media/cover-saturn.jpg",
    cuts: COSMOS_CUTS,
    stills: COSMOS_STILLS,
  },
];

export const SERIES_LABEL: Record<Cut["series"], { title: string; en: string }> = {
  crystal: { title: "水晶", en: "Crystal" },
  glass: { title: "玻璃", en: "Glass" },
};

export function getModule(id: string) {
  return MODULES.find((item) => item.id === id) ?? MODULES[0];
}
